apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
spec:
  limits:
  - default:
      cpu: 3
      memory: "1000Mi"
    defaultRequest:
      cpu: 1.5
      memory: "500Mi"
    type: Container
